### ISSUE TITLE
C++ version

### ISSUE THREAD

**Issue by Xiahuahui** [Cyril-Grelier/gc_wvcp_mcts#1]
What version of C++ is used for this project？ Thank you！

**Comment by Cyril-Grelier** [comment]
Hi, I'm building the project with [cmake](https://cmake.org/) (see the commands in the [build script](https://github.com/Cyril-Grelier/gc_wvcp_mcts/blob/master/scripts/build.sh) and the [CMakeLists file](https://github.com/Cyril-Grelier/gc_wvcp_mcts/blob/master/CMakeLists.txt)) and it uses C++17 (but C++14 should be enough I think) currently with gcc11 (I used gcc 8.3 for the experiments presented in the article but since then I've updated a lot of parts of the project and some of the algorithms are a bit more efficient).
You should use CMake to build the project as it download and build the cxxopts library (to handle the command line arguments) and the fmt library (for the printing and logging part) by itself (doing it manually is a pain and these libraries are very useful).

**Comment by Xiahuahui** [comment]
Are you make some changes to algorithm ‘ redls‘ such as Tabu instead of CC？
How about the time consuming of algorithm “redls”  for graphs with fewer vertices？
Thank you！

**Comment by Cyril-Grelier** [comment]
I didn't really change the redls algorithm, I just changed the implementation of some parts (comparing to the way I implemented it the first time), the "logic" of the algorithm remains the same as described in the redls article, with the 3 candidate sets and the 2 selection rules with a tabu list managed as a CC (I called it tabu_list in the code but it is a boolean array with the CC logic).
It's a bit more efficient compared to what I had at the time of the runs presented in the article, before, the Solution class handled special cases for each algorithm(unassigned vertices for ilsts, weights on edges for redls,...), now, ilsts and redls have a proxi Solution that handles these special cases (which is faster).
I don't really know what the differences are in terms of time compared to the original redls code, I had some problems running it (it was crashing with some graphs or random seeds and I couldn't figure out how to debug it) but the results are close to the results presented in the RedLS or ILSTS articles, there are still some small differences on the best score found, sometimes better, sometimes worse but I don't think it's a surprising difference because it's mainly due to the random part of these algorithms and the speed of the CPU used to run it.
But if you find out that I made a mistake reproducing the code, please tell me (Im sorry I didn't leave a lot of comments and some comments on the functions may not be up to date due to the recent modifications...).

**Comment by Xiahuahui** [comment]
Your code is very good, due to my time recently can not see too detailed! Thank you very much!

**Comment by Cyril-Grelier** [comment]
Thank you !
